FROM registry.redhat.io/ubi8/python-39

USER 0
WORKDIR /app
COPY . .

RUN pip install --upgrade pip && \
pip --no-cache-dir install -r requirements.txt

# create arbitrary group for user 1001
RUN groupadd -g 1001 default && usermod -g 1001 default

RUN chgrp -R 1001 /app && \
chmod -R g=u /app

USER 1001

RUN python3 model.py

EXPOSE 5000
CMD [ "python3", "-u", "app.py" ]
